config/routes.rb
Rails.application.routes.draw do
  resources :documents
    resources :procedure_types
    resources :list_categories, except: [:show]
    resources :reports, except: [:new,:index]
    get 'reports/new/:procedure_id' => 'reports#new'
    resources :announcements
    resources :verified_lists
    root 'static_pages#home'

    resources :verification_lists

    devise_for :users

    get '/logout' => 'static_pages#logout'

    get '/procedures/begin' => 'procedures#begin'
    post '/procedures/new' => 'procedures#new'
    get '/procedures/assign' => 'procedures#assign'
    post 'procedures/pick_verif_list' => 'verified_lists_controller#create'
    post '/procedures/:id/update' => 'procedures#update'
    post '/procedures/:id/send' => 'procedures#send_to_chief'
    post '/procedures/:id/finish' => 'procedures#finish'
    resources :procedures, except: [:update, :new]

    resources :users
    resources :companies
    resources :projects
    resources :roles

  get '/legal_agents/new/:company_id' => 'legal_agents#new2'
  resources :legal_agents ,except: [:update]
    post '/legal_agents/:id/update' => 'legal_agents#update'

    resources :employees
    post '/employees/:id/update' => 'employees#update'
    get '/employees/:id/update' => 'employees#edit'

    get '/orders/subregion_options' => 'static_pages#subregion_options'

    get '/users/annul/:id' => 'users#annul'
    get '/users/activate/:id' => 'users#activate'

    post '/createuser' => 'users#create'
    get '/verify/:id' => 'verified_lists#verify'

    get '/employeeAnnouncements' => 'announcements#employeeAnnouncements'
    get '/:dummy' => 'static_pages#error'
    get '/fonts/:dummy' => 'static_pages#error'
    get '/assets/underscore-min.map' => 'static_pages#error'

end

app/models/legal_agent.rb
class LegalAgent < ActiveRecord::Base
		belongs_to :person, :dependent => :destroy
		belongs_to :company
		has_many :procedures, :dependent => :destroy

		def self.search(search)
			where('first_name LIKE :search OR last_name LIKE :search', search:"%#{search}%")
		end


end

app/controllers/legal_agents_controller.rb
class LegalAgentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_legal_agent, only: [:show, :edit, :update, :destroy]
  before_action :verify_password_change
  before_action :verify_role

  def index
    if params[:search]
      @legal_agents = LegalAgent.joins(:person).search(params[:search]).order('created_at DESC')
    else
      @legal_agents = LegalAgent.all#.order('created_at DESC')
    end
  end

  # GET /legal_agents/1
  # GET /legal_agents/1.json
  def show
  end

  # GET /legal_agents/new
  def new
    @user = User.new
    @person = Person.new
    @companies = Company.all
  end

  def new2
    @user = User.new
    @person = Person.new
    @companies = Company.all
    @company = Company.find(params[:company_id])
  end

  # GET /legal_agents/1/edit
  def edit
    @legal_agent = LegalAgent.find(params[:id])
    @person = Person.find(@legal_agent.person_id)
    @companies = Company.all
    @user = User.find(@person.user_id)
  end

  # POST /legal_agents
  # POST /legal_agents.json
  def create
    if params[:company_id]
      @company = Company.find(params[:company_id])
    end
    @companies = Company.all
    @person = Person.new(person_params)
    @user = User.new(user_params)
    respond_to do |format|
      if @person.valid?
          @company = Company.find(params[:legal_agent][:company_id])
          @user.username = @person.get_username
          @user.password = @person.get_password (@company.name)
          @user.active = true
          if @user.valid?
              @user.save
              @person.identification_type = 1
              @person.user_id = @user.id
              @person.save
              @legal_agent = LegalAgent.new(legal_agent_params)
              @legal_agent.person_id = @person.id
              @legal_agent.save
              format.html { redirect_to @legal_agent, notice: 'Representante legal creado exitosamente' }
          else
            if params[:company_id]
              format.html { render :new2 }
            else
              format.html { render :new }
            end
          end
      else
        if params[:company_id]
          format.html { render :new2 }
        else
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /legal_agents/1/update
  def update
    @companies = Company.all
    @legal_agent = LegalAgent.find(params[:id])
    @person = Person.find(@legal_agent.person_id)
    @user = User.find(@person.user_id)
    respond_to do |format|
      if @person.update_attributes(person_params)
        @company = Company.find(params[:legal_agent][:company_id])
        @user.username = @person.get_username
        @user.password = @person.get_password (@company.name)
        if @user.update_attributes(user_params)
           @legal_agent.update_attributes(legal_agent_params)
           format.html { redirect_to @legal_agent, notice: 'Representante legal actualizado exitosamente' }
        else
          format.html { render :new }
        end
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /legal_agents/1
  # DELETE /legal_agents/1.json
  def destroy
    @legal_agent.destroy
    respond_to do |format|
      format.html { redirect_to legal_agents_url, notice: 'Representante Legal eliminado' }
      format.json { head :no_content }
    end
  end

  def verify_role
  if user_signed_in?
    if current_user.role==1  || current_user.role == 2
      [ :edit, :index, :new, :show]
    elsif current_user.role==1
        [ :show]
    else
      redirect_to root_url
    end
   end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_agent
      @legal_agent = LegalAgent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def legal_agent_params
      params.require(:legal_agent).permit(:company_id)
    end

    def person_params
      params.require(:person).permit(:identification_number, :identification_type, :first_name, :last_name, :phone_number, :country, :city, :address)
    end

    def user_params
      params.require(:user).permit(:role, :email, :active)
    end

end

app/helpers/legal_agents_helper.rb
module LegalAgentsHelper
end

app/views/legal_agents/_form.html.erb
<% if !@companies.any? %>
    <br/>
    <div class="row center actions">
      <div class="panel panel-danger">
        <div class="panel-heading">
          En este momento no se pueden registrar representantes legales ya que no existen companias registradas,
          registra una compania <%= link_to :aqui, :new_company %>.
        </div>
      </div>
    </div>

<% else %>

    <%if not params[:id]%>
        <%=form_tag controller:'legal_agents' %>
    <%else%>
        <%= form_tag 'update'%>
    <%end%>

      <% if @person.errors.any? or @user.errors.any?%>
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="panel panel-danger">
            <div class="panel-heading">Errores al registrar representante legal</div>
              <ul class="list-group">
                <% @person.errors.full_messages.each do |message| %>
                    <li class="list-group-item"><%= message %></li>
                <% end %>
                <% @user.errors.full_messages.each do |message| %>
                    <li class="list-group-item"><%= message %></li>
                <% end %>
              </ul>
          </div>
        </div>
      <% end %>
    <br>

        <%= hidden_field :legal_agent, :id  %>
        <%= hidden_field :user, :role , :value=>3  %>
        <%= hidden_field :user, :active, :value=>true  %>

        <div class="row">
          <div class="col-md-6">
            <div class="field">
              <label>Compa&ntilde;ia</label> <br/>
              <%if params[:company_id]%>
                  <h4><%= @company.name %></h4>
                  <%= hidden_field :legal_agent, :company_id, value:params[:company_id]%>
                  <%= hidden_field_tag :company_id, params[:company_id].to_s %>
              <%else%>
                  <%= select :legal_agent, :company_id, options_from_collection_for_select(@companies,'id','name'), {}, :class=>'form-control'%>
              <%end%>
            </div><br>
                <div class="field">
                  <label>Numero de Identificacion </label> <i class="fa fa-asterisk"></i> <br>
                  <%= text_field :person, :identification_number, :class => 'form-control' %>
                </div><br>
                <div class="field">
                  <label>Nombre</label> <i class="fa fa-asterisk"></i><br>
                  <%= text_field :person, :first_name, :class => 'form-control' %>
                </div><br>
                <div class="field">
                  <label>Apellido</label> <i class="fa fa-asterisk"></i><br>
                  <%= text_field :person, :last_name, :class => 'form-control' %>
                </div><br>
                <div class="field">
                  <label>Telefono</label> <i class="fa fa-asterisk"></i><br>
                  <%= text_field :person, :phone_number, :class => 'form-control' %>
                </div><br>
          </div>

          <div class="col-md-6">
                <div class="field">
                  <label>Correo electronico</label> <i class="fa fa-asterisk"></i><br>
                  <%= text_field :user, :email, :class=>'form-control'%>
                </div><br>

                <div class="field">
                  <div class="field">
                    <%= label_tag :pais %><br />
                    <%= country_select :person, :country, priority: %w(BO), prompt: 'Seleccione un pais', onload: 'loadCountries()' %>
                  </div>
                </div><br>

                <div class="field">
                  <div class="field">
                    <%= label_tag :ciudad %><br />
                    <%= hidden_field :person, :city  %>
                    <%= render partial: 'static_pages/subregion_select' %>
                  </div>
                </div><br>

                <div class="field">
                  <label>Direccion</label> <i class="fa fa-asterisk"></i><br>
                  <%= text_field :person, :address, :class => 'form-control' %>
                </div><br>
          </div>
        </div>
        <div class="panel panel-info">
          <div class="panel-heading"><i class="fa fa-asterisk"></i> Indica campo obligatorio</div>
        </div>
        <div class="row center">
          <div class="actions">
            <%= submit_tag 'Registrar',class: 'btn btn-default ' %>
          </div>
        </div>
    <br>
    <% #end %>

<script type="text/javascript" charset="utf-8">
    loadCountries();
</script>


<% end %>

app/views/legal_agents/edit.html.erb
<h1>Editar Representante Legal</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @legal_agent %> |
<%= link_to 'Back', legal_agents_path %>-->

app/views/legal_agents/index.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<div class="row">
  <div class="col-md-7">
    <h1>Buscar Representante Legal </h1>
    <br>
  </div>
  <div class="col-md-5">
      <%= render :partial => 'legal_agents/search' %>
      <div class="form-inline">
        <br>
        <%= form_tag( legal_agents_path , :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Nombre o Apellido", :class=>'form-control' %>
            <%= submit_tag "Buscar" ,:class=>'btn btn-default'%>
        <% end %>
      </div>
  </div>
</div>
<h1>Lista de Representantes Legales</h1>
<br>
<%if not @legal_agents.present? %>
    <div class="row center actions panel panel-danger">
      <div class="panel-heading">
        <% if params[:search] %>
            <p>Su busqueda no genero resultados</p>
        <%else%>
            <p>No existen representantes legales registrados este momento</p>
        <%end%>
      </div>
    </div>
<%else%>
    <br>
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>Nombre(s)</th>
        <th>Apellido(s)</th>
        <th>No. de Identificacion </th>
        <th>Telefono</th>
        <th>Usuario</th>
        <th>Compania</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody class="cream-pixels">
      <% @legal_agents.each do |legal_agent| %>
          <tr>
            <td><%= legal_agent.person.first_name %></td>
            <td><%= legal_agent.person.last_name %></td>
            <td><%= legal_agent.person.identification_number %></td>
            <td><%= legal_agent.person.phone_number %></td>
            <td><%= legal_agent.person.user.username %></td>
            <td><%= link_to legal_agent.company.name, legal_agent.company%></td>
            <td><%= link_to 'Ver', legal_agent, class:'btn btn-default' %></td>
            <td><%= link_to 'Editar', edit_legal_agent_path(legal_agent), class:'btn btn-primary' %></td>
            <%if current_user.role==1 or current_user.role==4 %>
                <td><%= link_to 'Eliminar', legal_agent, method: :delete, data: { confirm: 'Confirmacion' },class:'btn btn-danger' %></td>
            <%end%>
          </tr>
      <% end %>
      </tbody>
    </table>
<%end%>

<br>


<!--<%= link_to 'New Legal agent', new_legal_agent_path %>-->

app/views/legal_agents/new.html.erb

<h1>Registrar Representante Legal</h1>

<% if !@companies.any? %>
    <br/>
    <div class="row center actions">
      <div class="panel panel-danger">
        <div class="panel-heading">
          En este momento no se pueden registrar representantes legales ya que no existen companias registradas,
          registra una compania <%= link_to :aqui, :new_company %>.
        </div>
      </div>
    </div>

<% else %>

    <%if not params[:id]%>
        <%=form_tag controller:'legal_agents' %>
    <%else%>
        <%= form_tag 'update'%>
    <%end%>

    <% if @person.errors.any? or @user.errors.any?%>
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="panel panel-danger">
            <div class="panel-heading">Errores al registrar representante legal</div>
            <ul class="list-group">
              <% @person.errors.full_messages.each do |message| %>
                  <li class="list-group-item"><%= message %></li>
              <% end %>
              <% @user.errors.full_messages.each do |message| %>
                  <li class="list-group-item"><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>
    <br>

    <%= hidden_field :legal_agent, :id  %>
    <%= hidden_field :user, :role , :value=>3  %>
    <%= hidden_field :user, :active, :value=>true  %>

    <div class="row">
      <div class="col-md-6">
        <div class="field">
          <label>Compa&ntilde;ia</label> <br/>
              <%= select :legal_agent, :company_id, options_from_collection_for_select(@companies,'id','name'), {}, :class=>'form-control'%>
        </div><br>
        <div class="field">
          <label>Numero de Identificacion </label> <i class="fa fa-asterisk"></i> <br>
          <%= text_field :person, :identification_number, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Nombre</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :first_name, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Apellido</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :last_name, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Telefono</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :phone_number, :class => 'form-control' %>
        </div><br>
      </div>

      <div class="col-md-6">
        <div class="field">
          <label>Correo electronico</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :user, :email, :class=>'form-control'%>
        </div><br>

        <div class="field">
          <div class="field">
            <%= label_tag :pais %><br />
            <%= country_select :person, :country, priority: %w(BO), prompt: 'Seleccione un pais', onload: 'loadCountries()' %>
          </div>
        </div><br>

        <div class="field">
          <div class="field">
            <%= label_tag :ciudad %><br />
            <%= hidden_field :person, :city  %>
            <%= render partial: 'static_pages/subregion_select' %>
          </div>
        </div><br>

        <div class="field">
          <label>Direccion</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :address, :class => 'form-control' %>
        </div><br>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading"><i class="fa fa-asterisk"></i> Indica campo obligatorio</div>
    </div>
    <div class="row center">
      <div class="actions">
        <%= submit_tag 'Registrar',class: 'btn btn-default ' %>
      </div>
    </div>
    <br>
    <% #end %>

    <script type="text/javascript" charset="utf-8">
        loadCountries();
    </script>


<% end %>

app/views/legal_agents/new2.html.erb
<h1>Registrar Representante Legal </h1>

<% if !@companies.any? %>
    <br/>
    <div class="row center actions">
      <div class="panel panel-danger">
        <div class="panel-heading">
          En este momento no se pueden registrar representantes legales ya que no existen companias registradas,
          registra una compania <%= link_to :aqui, :new_company %>.
        </div>
      </div>
    </div>

<% else %>

    <%=form_tag controller:'legal_agents' %>

    <% if @person.errors.any? or @user.errors.any?%>
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <div class="panel panel-danger">
            <div class="panel-heading">Errores al registrar representante legal</div>
            <ul class="list-group">
              <% @person.errors.full_messages.each do |message| %>
                  <li class="list-group-item"><%= message %></li>
              <% end %>
              <% @user.errors.full_messages.each do |message| %>
                  <li class="list-group-item"><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>
    <br>

    <%= hidden_field :legal_agent, :id  %>
    <%= hidden_field :user, :role , :value=>3  %>
    <%= hidden_field :user, :active, :value=>true  %>

    <div class="row">
      <div class="col-md-6">
        <div class="field">
          <label>Compa&ntilde;ia</label> <br/>
              <h4><%= @company.name %></h4>
              <%= hidden_field :legal_agent, :company_id, value:params[:company_id]%>
              <%= hidden_field_tag :company_id, params[:company_id].to_s %>
        </div><br>
        <div class="field">
          <label>Numero de Identificacion </label> <i class="fa fa-asterisk"></i> <br>
          <%= text_field :person, :identification_number, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Nombre</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :first_name, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Apellido</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :last_name, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Telefono</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :phone_number, :class => 'form-control' %>
        </div><br>
      </div>

      <div class="col-md-6">
        <div class="field">
          <label>Correo electronico</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :user, :email, :class=>'form-control'%>
        </div><br>

        <div class="field">
          <div class="field">
            <%= label_tag :pais %><br />
            <%= country_select :person, :country, priority: %w(BO), prompt: 'Seleccione un pais', onload: 'loadCountries()' %>
          </div>
        </div><br>

        <div class="field">
          <div class="field">
            <%= label_tag :ciudad %><br />
            <%= hidden_field :person, :city  %>
            <%= render partial: 'static_pages/subregion_select' %>
          </div>
        </div><br>

        <div class="field">
          <label>Direccion</label> <i class="fa fa-asterisk"></i><br>
          <%= text_field :person, :address, :class => 'form-control' %>
        </div><br>
      </div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading"><i class="fa fa-asterisk"></i> Indica campo obligatorio</div>
    </div>
    <div class="row center">
      <div class="actions">
        <%= submit_tag 'Registrar',class: 'btn btn-default ' %>
      </div>
    </div>
    <br>
    <% #end %>

    <script type="text/javascript" charset="utf-8">
        loadCountries();
    </script>


<% end %>

app/views/legal_agents/show.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<h1>Ver Representante Legal</h1>

<div class="jumbotron">
  <table class="table">
    <tr>
      <td> <strong>Nombre</strong> </td>
      <td> <%= @legal_agent.person.first_name %> </td>
      <td> <strong>Apellido</strong> </td>
      <td> <%= @legal_agent.person.last_name %> </td>
    </tr>

    <tr>
      <td> <strong>Numero de identificacion</strong> </td>
      <td> <%= @legal_agent.person.identification_number %> </td>
      <td> <strong>Estado de usuario</strong> </td>
      <td> <%if @legal_agent.person.user.active%> Activo <%else%> Desactivo <%end%></td>
    </tr>
    <tr>
      <td> <strong>Pais</strong> </td>
      <td> <%= Carmen::Country.coded(@legal_agent.person.country) %> </td>
      <td> <strong>Ciudad</strong> </td>
      <td> <%= if !Carmen::Country.coded(@legal_agent.person.country).subregions.empty? then Carmen::Country.coded(@legal_agent.person.country).subregions.coded(@legal_agent.person.city) else @legal_agent.person.city end %> </td>
    </tr>

    <tr>
      <td> <strong>Direccion</strong> </td>
      <td> <%= @legal_agent.person.address %> </td>
      <td> <strong>Telefono</strong> </td>
      <td> <%= @legal_agent.person.phone_number %> </td>
    </tr>
    <tr>
      <td> <strong>Compania</strong> </td>
      <td> <%=link_to @legal_agent.company.name, @legal_agent.company %> </td>
      <td> <strong>Nombre de Usuario</strong> </td>
      <td> <%=@legal_agent.person.user.username%></td>
    </tr>
    <tr>
      <td> <strong>Correo electronico</strong> </td>
      <td> <%= @legal_agent.person.user.email %> </td>
      <td></td>
      <td></td>
    </tr>
  </table>

</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <strong>Informacion de acceso a sistema generada automaticamente</strong>
        <br/>Nombre de usuario: [numero_de_identificacion]_[nombre(s)], los espacios son sustituidos por '_'
        <br/>Contrase&ntilde;a: [nombre_de_compa&ntilde;ia]_[nombre(s)], los espacios son sustituidos por '_'
        <br> Click en nombre de compa&ntilde;ia para ver detalles 
  </div>
</div>

<<<<<<< HEAD
<div class="row">
  <div class="col-xs-6 col-sm-3  "></div>
  <div class="col-xs-6 col-sm-3 ">
    <%= link_to 'Editar', edit_legal_agent_path(@legal_agent), :class=>'btn btn-primary'%>
  </div>  
  <div class="col-xs-6 col-sm-3  ">
    <%= link_to 'Volver a registrar proyecto', new_project_path ,class: 'btn btn-info'%>
  </div>     
</div>
