config/routes.rb
Rails.application.routes.draw do
  resources :documents
    resources :procedure_types
    resources :list_categories, except: [:show]
    resources :reports, except: [:new,:index]
    get 'reports/new/:procedure_id' => 'reports#new'
    resources :announcements
    resources :verified_lists
    root 'static_pages#home'

    resources :verification_lists

    devise_for :users

    get '/logout' => 'static_pages#logout'

    get '/procedures/begin' => 'procedures#begin'
    post '/procedures/new' => 'procedures#new'
    get '/procedures/assign' => 'procedures#assign'
    post 'procedures/pick_verif_list' => 'verified_lists_controller#create'
    post '/procedures/:id/update' => 'procedures#update'
    post '/procedures/:id/send' => 'procedures#send_to_chief'
    post '/procedures/:id/finish' => 'procedures#finish'
    resources :procedures, except: [:update, :new]

    resources :users
    resources :companies
    resources :projects
    resources :roles

  get '/legal_agents/new/:company_id' => 'legal_agents#new2'
  resources :legal_agents ,except: [:update]
    post '/legal_agents/:id/update' => 'legal_agents#update'

    resources :employees
    post '/employees/:id/update' => 'employees#update'
    get '/employees/:id/update' => 'employees#edit'

    get '/orders/subregion_options' => 'static_pages#subregion_options'

    get '/users/annul/:id' => 'users#annul'
    get '/users/activate/:id' => 'users#activate'

    post '/createuser' => 'users#create'
    get '/verify/:id' => 'verified_lists#verify'

    get '/employeeAnnouncements' => 'announcements#employeeAnnouncements'
    get '/:dummy' => 'static_pages#error'
    get '/fonts/:dummy' => 'static_pages#error'
    get '/assets/underscore-min.map' => 'static_pages#error'

end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :procedure_types, :through => :requirements
  has_many :requirements, :dependent => :destroy

  has_many :verification_lists, :through => :revisions
  has_many :revisions, :dependent => :destroy

  has_many :received_documents, :dependent => :destroy

  accepts_nested_attributes_for :revisions, :reject_if => :all_blank, :allow_destroy => true
  before_validation :uppercase
  validates :typename, presence: {message:'no debe dejarse en blanco'}
  validates :typename, uniqueness: {message: 'ya existe, no se debe repetir'}

  def self.search(search)
    where("typename LIKE :search ", search:"%#{search}%")
  end
protected
def uppercase
  self.typename = self.typename.upcase
end  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    if current_user.role == 1
      @documents = Document.all.paginate(:page => params[:page], :per_page => 10)
      if params[:search]
        @documents = Document.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
      else
        @documents = Document.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
      end
    else
      redirect_to root_url
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    #@verification_lists= Document.verification_lists
    Revision.delete_null_fields
  end

  # GET /documents/new
  def new
    @document = Document.new
    @verification_lists = VerificationList.all
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.typename= @document.typename.upcase
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'El documento fue registrado exitosamente' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'El documento fue actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'El Documento fue eliminado' }
      format.json { head :no_content }
    end
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:typename, revisions_attributes: [:id, :verification_list_id])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
    <% if @document.errors.any? %>
        <div class="col-md-3"></div>
        <div class="col-md-6">

          <div class="panel panel-danger">
            <div class="panel-heading">Errores al registrar documento</div>
            <ul class="list-group">
              <% @document.errors.full_messages.each do |message| %>
                  <li class='list-group-item'><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="col-md-3"></div>
    <% end %>

    <div class="row">
        <div class="col-md-6">
          <br><br><br><br><br>
          <div class="field">
            <%= f.label :Nombre %> <i class="fa fa-asterisk"></i><br>
            <%= f.text_field :typename, class: 'form-control' %>
          </div>
          <br>
          <div class="actions">
            <%= f.submit :Registrar, class: 'btn btn-default', id: 'document-submit-button'%>
          </div>
        </div>
      <!-- VERIFICATION LIST FIELDS WRAPPER -->
        <div class="col-md-6">
         <h2>Listas de Verificación necesarias para revisar el documento.</h2>

          <div class="col-md-12" id="lists-error-div" style="display: none">
            <div class="panel panel-danger">
              <div class="panel-heading">Errores al agregar listas de verificación</div>
              <ul class="list-group" id="lists-errors">
              </ul>
            </div>
          </div>

            <% if VerificationList.all.count == 0 %>
              <div class="row center actions panel panel-danger">
                <div class="panel-heading">
                  <p>No existen listas de verificacion por el momento, registra <%=link_to :aquí, new_verification_list_path %> </p>
                </div>
              </div>
            <%else%>

              <div class="field" id="list-options-template" style="display: none ;">
                <% VerificationList.all.each do |list| %>
                    <option value="<%= list.id %>"><%= list.name %></option>
                <% end %>
              </div>

              <div class="col-md-offset-1 row" id="verification-list-fields">
                <label >Existe(n) <label id="verification-list-count" ><%= if @count then @count else '0' end %></label> campo(s) de verificación en total</label>
                <%= f.fields_for :revisions do |builder| %>
                    <%= render 'revision_field', :f => builder %>
                <% end %>
                <br>
              </div>

              <div class="field">
                <a class="btn btn-success" onclick="addVerificationList()"> Agregar Lista de Verificación</a>
              </div>
          <% end %>

          <br>
        </div>
    </div>
    <br/>
<% end %>

<script>
    var verificationListsCount = 0;
    var toShowCount = $('.revisionField').length;

    $('#document-submit-button').on('click', function(event){
        var revision = $('.revisionField :selected').filter(function() { return $(this).parent().parent().parent().css("display") != "none" });

        if(revision.length == 0){
            event.preventDefault();
            $('#lists-error-div').css({"display": "block"});
            if($('#one-list-error').length == 0){
                $('#lists-errors').append('<li class="list-group-item" id="one-list-error">Debe seleccionar al menos una lista de verificación.</li>');
            }
        }
        else{
            $('#lists-error-div').css({"display": "none"});
            $('#one-list-error').remove();
        }
        var revisionValues = [];
        revision.each(function(){
            revisionValues.push(parseInt($(this).val()));
        });
        revisionValues = revisionValues.sort();
        var i;
        for (var i = 0; i < revisionValues.length - 1; i++) {
            if (revisionValues[i + 1] == revisionValues[i]) {
                event.preventDefault();
                $('#lists-error-div').css({"display": "block"});
                if($('#repeated-list-error').length == 0){
                    $('#lists-errors').append('<li class="list-group-item" id="repeated-list-error">Los documentos seleccionados no pueden repetirse.</li>');
                }
            }
            else{
                $('#lists-error-div').css({"display": "none"});
                $('#repeated-list-error').remove();
            }
        }

//        if(i == revisionValues.max_line_len){
//            $('#lists-error-div').css({"display": "none"});
//            $('#repeated-list-error').remove();
//        }

    });

    function checkListCount(){
        if($('.revisionField').length != 0){
            verificationListsCount = $('.revisionField').length;
            toShowCount = verificationListsCount;
        }
        else
            verificationListsCount = 0;
    }

    function addVerificationList(){
        checkListCount();
        var listField = '<div class="field"><label for="document_revisions_attributes_'+verificationListsCount+'_verification_list_id">Lista de Verificacion</label><br><div class="col-xs-10"><select class="form-control revisionField" name="document[revisions_attributes]['+verificationListsCount+'][verification_list_id]" id="document_revisions_attributes_'+verificationListsCount+'_verification_list_id">'+$('#list-options-template').html()+'</select></div><a onclick="deleteVerificationField('+verificationListsCount+')" class="btn btn-danger"><i class="fa fa-times-circle"></i></a><br><br></div>';
        $('#verification-list-fields').append(listField);
        verificationListsCount++;
        toShowCount++;
        checkListCount();
        $('#verification-list-count').text(parseInt($('#verification-list-count').text())+1);
        stabilize();
    }

    function deleteVerificationField(listField){
        $('#document_revisions_attributes_'+listField+'_verification_list_id').parent().parent().css('display', 'none');
        $('#document_revisions_attributes_'+listField+'_verification_list_id :selected').attr('value', '');
        toShowCount--;
        checkListCount();
        $('#verification-list-count').text(parseInt($('#verification-list-count').text())-1);
    }

    function setDeleteFields(){
        checkListCount();
        var deletes = $('.to-fix');
        deletes.each(function(index){
            $(this).attr('onclick','deleteVerificationField('+index+')');
        });
    }

    setDeleteFields();

    function setDocCountValue(){
        $('#verification-list-count').text(toShowCount);
    }

    setDocCountValue();

</script>

app/views/documents/_revision_field.html.erb
<div class="field">
  <%= f.label :verification_list_id, 'Lista de Verificacion' %><br>
  <div class="col-xs-10">
    <%= f.select :verification_list_id, options_from_collection_for_select(VerificationList.all, :id, :name, f.object.verification_list_id) ,{} ,class: 'form-control revisionField' %>
  </div>
  <a class="btn btn-danger to-fix"><i class="fa fa-times-circle"></i></a>
  <br><br>
</div>

app/views/documents/edit.html.erb
<h1>Editar Documento</h1>

<%= render 'form' %>

<%= link_to 'Ver', @document , class:'btn btn-default'%>
<%= link_to 'Volver', documents_path , class:'btn btn-default'%>

app/views/documents/index.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<div class="row">
  <div class="col-md-7">
    <h1>Lista de Documentos</h1>
  </div>
  <div class="col-md-5">
    <%= render :partial => 'documents/search' %>
    <br>
        <div class="form-inline">
              <%= form_tag(documents_path, :method => "get", id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Nombre de documento", :class => 'form-control'%>
                  <%= submit_tag 'Buscar', :class=>'btn btn-default' %>
              <% end %>
        </div>
  </div>
</div>
    <%if @documents.empty?%>
        <div class="row center actions">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <% if params[:search] %>
                  <p>Su busqueda no generó resultados</p>
              <%else%>
                  <p>No existen Documentos registrados en este momento</p>
              <%end%>
            </div>
          </div>
        </div>
    <% else %>
    <div class="col-md-6 col-md-offset-3">
      <div class="digg_pagination">
        <%= will_paginate @documents,  :previous_label => 'Atras', :next_label => 'Siguiente', :container => true ,renderer: BootstrapPagination::Rails%>
      </div>
    </div><br>
        <table class="table table-stripped table-hover">
          <thead>
            <tr>
              <th>Nombre</th>
              <th># Listas</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody class="cream-pixels">
            <% @documents.each do |document| %>
              <tr>
                <td><%= document.typename %></td>
                <td><%= document.verification_lists.count %> </td>
                <td><%= link_to 'Ver', document , class:'btn btn-default'%></td>
                <td><%= link_to 'Editar', edit_document_path(document) , class:'btn btn-primary'%></td>
                <td><%= link_to 'Eliminar', document, method: :delete, data: { confirm: 'Esta seguro?' } , class:'btn btn-danger'%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="col-md-6 col-md-offset-3">
          <div class="digg_pagination">
            <%= will_paginate @documents,  :previous_label => 'Atras', :next_label => 'Siguiente', :container => true ,renderer: BootstrapPagination::Rails%>
          </div>
        </div><br>
    <%end%>
    <br>

app/views/documents/new.html.erb
<h1>Registrar documento para recepción</h1>

<%= render 'form' %>

app/views/documents/show.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<h1>Ver Documento</h1>
<br>

<div class='jumbotron col-md-12'>
    <h2> <%= @document.typename %> </h2>
    <hr>
    <br/>
    <h3>Listas de Verificacion necesarias para revisar ese documento:</h3>
    <div class="col-md-1"></div>
    <% if @document.verification_lists.empty? %>
        <div class="row center actions panel panel-danger">
          <div class="panel-heading">
            <p>No se encuentran listas de verificacion asociadas a este documento</p>
          </div>
        </div>
    <%else%>
        <div class="col-md-10">
          <table class="table table-striped table-hover">
            <thead>
            <tr>
              <th><strong>Nombre de la lista</strong></th>
            </tr>
            </thead>
            <tbody class="cream-pixels">
            <% @document.revisions.each do |list| %>
                <tr>
                  <td><%= list.verification_list.name %></td>
                  <td><%= link_to :Ver, list.verification_list, {class: 'btn btn-default'}%> </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>
  <div class="col-md-1"></div>
</div>

<div class="row">
  <%= link_to 'Editar', edit_document_path(@document), class:'btn btn-primary' %>
  <%= link_to 'Volver', documents_path, class:'btn btn-default' %>
</div>