config/routes.rb
Rails.application.routes.draw do
  resources :documents
    resources :procedure_types
    resources :list_categories, except: [:show]
    resources :reports, except: [:new,:index]
    get 'reports/new/:procedure_id' => 'reports#new'
    resources :announcements
    resources :verified_lists
    root 'static_pages#home'

    resources :verification_lists

    devise_for :users

    get '/logout' => 'static_pages#logout'

    get '/procedures/begin' => 'procedures#begin'
    post '/procedures/new' => 'procedures#new'
    get '/procedures/assign' => 'procedures#assign'
    post 'procedures/pick_verif_list' => 'verified_lists_controller#create'
    post '/procedures/:id/update' => 'procedures#update'
    post '/procedures/:id/send' => 'procedures#send_to_chief'
    post '/procedures/:id/finish' => 'procedures#finish'
    resources :procedures, except: [:update, :new]

    resources :users
    resources :companies
    resources :projects
    resources :roles

  get '/legal_agents/new/:company_id' => 'legal_agents#new2'
  resources :legal_agents ,except: [:update]
    post '/legal_agents/:id/update' => 'legal_agents#update'

    resources :employees
    post '/employees/:id/update' => 'employees#update'
    get '/employees/:id/update' => 'employees#edit'

    get '/orders/subregion_options' => 'static_pages#subregion_options'

    get '/users/annul/:id' => 'users#annul'
    get '/users/activate/:id' => 'users#activate'

    post '/createuser' => 'users#create'
    get '/verify/:id' => 'verified_lists#verify'

    get '/employeeAnnouncements' => 'announcements#employeeAnnouncements'
    get '/:dummy' => 'static_pages#error'
    get '/fonts/:dummy' => 'static_pages#error'
    get '/assets/underscore-min.map' => 'static_pages#error'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :legal_agents, :dependent => :destroy
  	has_many :projects, :dependent => :destroy
  	before_validation :uppercase
	validates :name, :presence => {:message => ' no debe dejarse en blanco.'}
	validates :name, length: {minimum:4, message:' debe tener como minimo cuatro caracteres'}
	validates :name, uniqueness: {message: ' ya existe, no se debe duplicar'}
	validates :principal_activity, :presence => {:message => ' no debe dejarse en blanco.'}
	validates :nit, :presence => {:message => ' no debe dejarse en blanco.'}
	validates :nit, uniqueness: {message: ' ya existe, no se debe duplicar'}
	validates :nit, numericality: { only_integer: true, message: ' debe ser un numero' }
	validates :address, :presence => {:message => ' no debe dejarse en blanco.'}
	validates :departament, :presence => {:message => ' no debe dejarse en blanco.'} 
	validates :phones, :presence => {:message => ' no debe dejarse en blanco.'} 
	validates :phones, numericality: { only_integer: true, message: ' debe ser un numero' }
	validates :email, allow_blank: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i , message: 'presenta un formato invalido'}

	def self.search(search)
		where("name LIKE :search ", search:"%#{search}%")
	end

	def self.get_companies_with_legal_agents
		@companies = Array.new
		Company.all.each do |company|
			if company.legal_agents.any?
				@companies << [company.name, company.id]
			end
		end
		@companies
	end
	protected
	def uppercase
	  self.name = self.name.upcase
	end	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :verify_password_change
  before_action :verify_role

  # GET /companies
  # GET /companies.json
  def index
       if params[:search]
          @companies = Company.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
       else
          @companies = Company.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
       end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.name = @company.name.upcase
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Compania registrada exitosamente' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
      @company.name = @company.name.upcase
    respond_to do |format|
      if @company.update(company_params)
          format.html { redirect_to @company, notice: 'Compania actualizada exitosamente' }
          format.json { render :show, status: :ok, location: @company }
        else
          format.html { render :edit }
          format.json { render json: @company.errors, status: :unprocessable_entity }
       end 
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Compañia eliminada' }
      format.json { head :no_content }
    end
  end

  def verify_role
    if user_signed_in?
      if current_user.role==2 || current_user.role == 1 || current_user.role == 4
        [ :edit, :index, :new, :show]
      else
        redirect_to root_url
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :principal_activity, :nit, :address, :zone, :departament, :phones, :email,)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div class="col-md-3"></div>
    <div class="col-md-6">
      
      <div class="panel panel-danger">
        <div class="panel-heading">Errores al registrar compañia</div>
          <ul class="list-group">
            <% @company.errors.full_messages.each do |message| %>
              <li class='list-group-item'><%= message %></li>
            <% end %>
          </ul>
      </div>
    </div>
  <% end %>
<br>

<div class="row">
      <div class="col-md-6">
        <div class="field">
          <label>Nombre <i class="fa fa-asterisk"></i></label><br>
          <%= f.text_field :name, :class => 'form-control'%>
        </div><br>
        <div class="field">
          <label>NIT <i class="fa fa-asterisk"></i></label><br>
          <%= f.text_field :nit, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Actividad principal <i class="fa fa-asterisk"></i></label><br>
          <%= f.text_field :principal_activity, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Direccion <i class="fa fa-asterisk"></i></label><br>
          <%= f.text_field :address, :class => 'form-control' %>
        </div><br>
      </div>
      <div class="col-md-6">
        <div class="field">
          <label>Zona</label><br>
          <%= f.text_field :zone, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Departamento <i class="fa fa-asterisk"></i></label><br>
          <%= f.select :departament, ['Cochabamba','Beni','La Paz','Oruro','Pando','Potosi','Santa Cruz','Sucre','Tarija'] ,{},:class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Correo electronico</label><br>
          <%= f.text_field :email, :class => 'form-control' %>
        </div><br>
        <div class="field">
          <label>Telefono <i class="fa fa-asterisk"></i></label><br>
          <%= f.text_field :phones, :class => 'form-control' %>
        </div><br>
      </div><br>

</div>

    <div class="panel panel-info">
      <div class="panel-heading"> <i class="fa fa-asterisk"></i> Indica campo obligatorio</div>
    </div>


   <div class="row center actions">
    <%= f.submit 'Registrar', class: 'btn btn-default ' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editar compañia</h1>

<%= render 'form' %>

<!--<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>-->

app/views/companies/index.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<div class="row">
  <div class="col-md-7">
    <h1>Buscar Compañia </h1>
    <br>
  </div>
  <div class="col-md-5">
      <%= render :partial => 'companies/search' %>
      <div class="form-inline">
        <br>
        <%= form_tag(companies_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Nombre de compañia", :class => 'form-control'%>
            <%= submit_tag 'Buscar', :class=>'btn btn-default' %>
        <% end %>
      </div>
  </div>
</div>
<h1>Lista de Compañias</h1>
<br>
<% if @companies.present? %>
<div class="col-md-4 col-md-offset-4">
  <div class="digg_pagination">
    <%= will_paginate @companies,  :previous_label => 'Atras', :next_label => 'Siguiente', :container => true ,renderer: BootstrapPagination::Rails%>
  </div>
</div><br>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>NIT</th>
        <th>Telefono</th>
        <th>Correo electronico</th>
        <th>#R.L.</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%=company.name%></td>
          <td><%= company.nit %></td>
          <td><%= company.phones %></td>
          <td><%if !company.email.blank? %>
                <%= company.email %>
            <%else%>
                No registrado
            <%end%>
          </td>
          <td><%=company.legal_agents.count%></td>
          <td><%= link_to 'Ver', company , class:'btn btn-default'%></td>
          <%if current_user.role==1 or current_user.role==2 %>
            <td><%= link_to 'Registrar R.L.', '/legal_agents/new/'+company.id.to_s ,class:'btn btn-info'%></td>
          <%end%>
            <td><%= link_to :Editar, edit_company_path(company), class:'btn btn-primary'%></td>
            <td><%= link_to 'Eliminar', company, method: :delete, data: { confirm: 'Esta seguro?' }, class:'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="col-md-4 col-md-offset-4">
    <div class="digg_pagination">
      <%= will_paginate @companies,  :previous_label => 'Atras', :next_label => 'Siguiente', :container => true ,renderer: BootstrapPagination::Rails%>
    </div>
  </div><br>
<%else%>
    <div class="row center actions panel panel-danger">
      <div class="panel-heading">
        <% if params[:search] %>
            <p>Su busqueda no generó resultados</p>
        <%else%>
            <p>No existen Compañias registradas este momento</p>
        <%end%>
      </div>
    </div>
<%end%>
<br>

<!--<%= link_to 'New Company', new_company_path %>-->

app/views/companies/new.html.erb
<h1>Registrar Compa&ntilde;ia</h1>

  <%= render 'form' %>

<!--<%= link_to 'Back', companies_path %>-->

app/views/companies/show.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<h1>Ver Compañia</h1>
  <br>
<%= link_to 'Editar', edit_company_path(@company), :class=>'btn btn-primary' %>

<br/><br/>

<div class='jumbotron'>
  <h3>Informacion de Compania</h3><br/>
  <table class='table'>
    <tr>
      <td> <strong>Nombre</strong> </td>
      <td> <%= @company.name %> </td>

      <td> <strong>Actividad principal</strong> </td>
      <td> <%= @company.principal_activity %> </td>
    </tr>
    <tr>
      <td> <strong>NIT</strong> </td>
      <td> <%= @company.nit %> </td>

      <td> <strong>Direccion</strong> </td>
      <td> <%= @company.address %> </td>
    </tr>

    <tr>
      <td> <strong>Zona</strong> </td>
      <td> <%= @company.zone %> </td>

      <td> <strong>Correo electronico</strong> </td>
      <td> <%= @company.email%> </td>
    </tr>
    <tr>
      <td> <strong>Departamento</strong> </td>
      <td> <%= @company.departament %> </td>

      <td> <strong>Telefono</strong> </td>
      <td> <%= @company.phones %> </td>
    </tr>

  </table>

  <br/>

  <% if @company.legal_agents.any? %>
      <h3>Representantes Legales asociados</h3><br/>
      <table class="table">
        <tr>
          <th>Apellido(s)</th>
          <th>Nombre(s)</th>
          <th>E-mail</th>
          <th>C.I.</th>
          <th></th>
        </tr>
        <%@company.legal_agents.each do |legal_agent|%>
            <tr>
              <td><%=legal_agent.person.last_name %></td>
              <td><%=legal_agent.person.first_name %></td>
              <td><%=legal_agent.person.user.email %></td>
              <td><%=legal_agent.person.identification_number %></td>
              <td><%=link_to 'Ver', legal_agent ,:class=>'btn btn-default'%></td>
            </tr>
        <%end%>
      </table>
  <%end%>

</div>

  <div class="row">
  <div class="col-xs-6 col-sm-3  "></div>
      <div class="col-xs-6 col-sm-3  ">
        <%= link_to 'Volver a registrar proyecto', new_project_path ,class: 'btn btn-primary'%>
      </div>  
    
      <div class="col-xs-6 col-sm-3 ">
        <%= link_to 'Registrar Representante Legal', '/legal_agents/new/'+@company.id.to_s ,class:'btn btn-info'%>
      </div>  
  </div>