config/routes.rb
Rails.application.routes.draw do
  resources :documents
    resources :procedure_types
    resources :list_categories, except: [:show]
    resources :reports, except: [:new,:index]
    get 'reports/new/:procedure_id' => 'reports#new'
    resources :announcements
    resources :verified_lists
    root 'static_pages#home'

    resources :verification_lists

    devise_for :users

    get '/logout' => 'static_pages#logout'

    get '/procedures/begin' => 'procedures#begin'
    post '/procedures/new' => 'procedures#new'
    get '/procedures/assign' => 'procedures#assign'
    post 'procedures/pick_verif_list' => 'verified_lists_controller#create'
    post '/procedures/:id/update' => 'procedures#update'
    post '/procedures/:id/send' => 'procedures#send_to_chief'
    post '/procedures/:id/finish' => 'procedures#finish'
    resources :procedures, except: [:update, :new]

    resources :users
    resources :companies
    resources :projects
    resources :roles

  get '/legal_agents/new/:company_id' => 'legal_agents#new2'
  resources :legal_agents ,except: [:update]
    post '/legal_agents/:id/update' => 'legal_agents#update'

    resources :employees
    post '/employees/:id/update' => 'employees#update'
    get '/employees/:id/update' => 'employees#edit'

    get '/orders/subregion_options' => 'static_pages#subregion_options'

    get '/users/annul/:id' => 'users#annul'
    get '/users/activate/:id' => 'users#activate'

    post '/createuser' => 'users#create'
    get '/verify/:id' => 'verified_lists#verify'

    get '/employeeAnnouncements' => 'announcements#employeeAnnouncements'
    get '/:dummy' => 'static_pages#error'
    get '/fonts/:dummy' => 'static_pages#error'
    get '/assets/underscore-min.map' => 'static_pages#error'

end

app/models/procedure.rb
class Procedure < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :procedure_type
  belongs_to :legal_agent
  has_one :report, :dependent => :destroy
  has_many :received_documents, :dependent=> :destroy


  # ESTADOS
  # 1 inicial
  # 2 en revision
  # 3 revisado
  # 4 aceptado
  # 5 rechazado

  def self.search(search)
    where("name LIKE :search ", search:"%#{search}%")
  end

  def get_documents_verified_list
    nil
  end

#  def is_documents_list_verified?
#    get_documents_verified_list.verified
#  end

  def has_documents_verified_list?
    verified_lists.each do |verified_list|
      if verified_list.verification_list.list_category_id==1
        return true
      end
    end
    false
  end

  def has_verified_lists?
    verified_lists.each do |verified_list|
      if verified_list.verification_list.list_category_id!=1
        return true
      end
    end
  false
  end

  def can_be_sent_to_chief?
    if report
      received_documents.each do |received_documents|
        if not received_documents.has_all_lists_verified?
          return false
        end
      end
      return true
    else
      return false
    end
  end

  def get_first_not_reviewed
    verified_lists.each do |verified_list|
      unless verified_list.verified
        return verified_list
      end
    end
    nil
  end

end

app/models/procedure_type.rb
class ProcedureType < ActiveRecord::Base
  has_many :procedures, :dependent => :destroy

  has_many :documents, :through => :requirements
  has_many :requirements, :dependent => :destroy
  before_validation :uppercase
  accepts_nested_attributes_for :requirements

  validates :name, presence: { :message => 'no debe dejarse en blanco' }
  validates :name, uniqueness: { :message => 'ya fue registrado, no puede repetirse' }
  validates :name, length: {minimum: 5, :message => 'no debe tener menos de 5 caracteres.'}
  validates :name, length: {maximum: 100, :message => 'no debe tener mas de 100 caracteres.'}

  def get_doc_reception_verif_list
    verification_lists.each do |verification_list|
      if verification_list.list_category_id == 1
        return verification_list
      end
    end
    verification_lists.first
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  def self.get_ones_with_documents
    @procedure_types = Array.new
    ProcedureType.all.each do |procedure_type|
      if procedure_type.documents.count>0
        @procedure_types << procedure_type
      end
    end
    @procedure_types
  end
  protected
  def uppercase
    self.name = self.name.upcase
  end 
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]
  before_action :verify_password_change

  def index
    @role_current_user = current_user.role
      if  @role_current_user == 1 || @role_current_user == 2 || @role_current_user == 4
        if params[:search]
          @procedures = Procedure.joins(:project).search(params[:search])
        else
          @procedures = Procedure.all#.order('created_at DESC')
        end
      elsif @role_current_user == 3
        @procedures = current_user.person.legal_agent.procedures
      else
        @procedures = current_user.procedures
      end
  end

  def begin
    @projects = Project.available_projects_for_procedure.reverse
    @procedure_types = ProcedureType.get_ones_with_documents
  end

  def new
    @reception_documents = ProcedureType.find(params[:procedure_type_id]).documents
    @project = Project.find(params[:project_id])
    @legal_agents = @project.company.legal_agents
    @procedure_type= ProcedureType.find(params[:procedure_type_id])
  end

  def show
  end

  def assign
    @role_current_user = current_user.role
      if  @role_current_user == 1 || @role_current_user == 4
        @procedures = Procedure.where(state:1)
        @users = User.where(role:5)
      else
        redirect_to root_url
      end
  end

  def send_to_chief
    @procedure = Procedure.find(params[:id])
    @procedure.state = 3
    @procedure.save
    redirect_to @procedure
  end

  def finish
    @procedure = Procedure.find(params[:id])
    @procedure.end_date = Date.today
    if params[:finished]=='yes'
      @procedure.state=4
    elsif params[:finished]=='no'
      @procedure.state=5
    end
    @procedure.save
    redirect_to @procedure
  end

  def show
  end

  def edit
    @role_current_user = current_user.role
      if @role_current_user == 5 || @role_current_user == 3 || @role_current_user == 1
        if params[:search]
          @procedures = Procedure.joins(:project).where(user_id: current_user.id ).search(params[:search])
        else
          @procedures= Procedure.joins(:project).where(user_id: current_user.id )
        end
      end
  end

  def create
    @procedure = Procedure.new(procedure_params)
    @procedure.state = 1
    @procedure.start_date = Time.now
    respond_to do |format|
      if @procedure.save
         @procedure_type = ProcedureType.find(params[:procedure][:procedure_type_id])
         @procedure_type.documents.each do |document|
           @received_document = ReceivedDocument.create(procedure_id:@procedure.id,document_id:document.id,reference:params[document.typename])
           @received_document.create_verified_lists
         end
        # @doc_reception_list = @procedure_type.get_doc_reception_verif_list
        # @verified_list = VerifiedList.create_verified_list(@doc_reception_list.id ,@procedure.id)
        format.html { redirect_to @procedure , notice: 'Tramite registrado exitosamente' }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: 'Tramite actualizado exitosamente' }
        format.json { render :index}
      end
    end
  end

  def destroy
    @procedure.destroy
    respond_to do |format|
      format.html { redirect_to procedures_url, notice: 'Tramite eliminado' }
      format.json { head :no_content }
    end
  end


  private
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    def procedure_params
      params.require(:procedure).permit(:project_id,:user_id,:state,:procedure_type_id,:legal_agent_id)
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_tag :procedures, method: 'post' do %>
    <%= hidden_field_tag 'procedure[procedure_type_id]', params[:procedure_type_id] %>
    <%= hidden_field_tag 'procedure[project_id]', params[:project_id] %>

<div class="row">
  <div class="col-md-4">
    <h3>Proyecto: <%= @project.name %></h3>
    <h4>Tipo de Trámite: <%= @procedure_type.name %></h4>
  </div>
  <div class="col-md-8">
    <div class="panel panel-info">
      <div class="panel-heading">Seleccione el Representante Legal</div>
      <ul class="list-group">
        <%@legal_agents.each do |legal_agent| %>
            <div class="radio">
              <li class="list-group-item">
                <label>
                  <%= radio_button :procedure, :legal_agent_id ,legal_agent.id, {checked:true}%>
                  <%= legal_agent.person.last_name%> <%= legal_agent.person.first_name%>
                </label>
              </li>
            </div><!-- /input-group -->
        <%end%>
      </ul>
    </div>
  </div>
</div>
<br/>

<div class="row" id="doc-error" style="display: none">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="panel panel-danger">
      <div class="panel-heading"> <p id="error-message"></p> </div>
    </div>
  </div>
</div>

<table class="table table-hovers">
    <thead>
      <tr>
        <th>Documento</th>
        <th>Referencia</th>
      </tr>
    </thead>

      <tbody class="cream-pixels">
        <% @reception_documents.each do |document| %>
            <tr>
              <td><%= document.typename %></td>
              <td><%= text_field_tag document.typename ,'', class:'form-control document-reception'%></td>
            </tr>
        <%end%>
      </tbody>
      <tr>
        <td colspan="2"><center><%= submit_tag :Registrar , class:'btn btn-default', id: 'start-procedure' %></center></td>
      </tr>
  <%end%>
</table>

<script>
  $('#start-procedure').on('click', function(event) {
    var references = $('.document-reception');
    for(var i = 0; i < references.length; i++){
      if (references[i].value == ""){
        event.preventDefault();
        $('#doc-error').css({ display:'block' });
        $('#error-message').text('Debe llenar todos los campos de referencia para poder iniciar el tramite.');
        break;
      }
    }
  });
</script>

app/views/procedures/assign.html.erb
<h1>Asignar tramite a revisor</h1>
<br/>
<h3>Tramites en estado inicial</h3>
<br/>
<%if @procedures.empty? %>
    <div class="row center actions">
      <div class="panel panel-danger">
        <div class="panel-heading">
          En este momento no hay tramites que necesiten asignacion de un revisor
        </div>
      </div>
    </div>
<%else%>
    <h4>Entre parentesis se presenta el numero de tramites que el empleado esta revisando actualmente</h4>
    <br/>
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Proyecto</th>
        <th>Revisor</th>
      </tr>
      </thead>
      <tbody>
      <% @procedures.each do |procedure| %>
          <tr>
            <td>(<%= procedure.project.company.name%>) <%= procedure.project.name %> </td>
            <td>
              <div class="form-inline">
                    <%=form_tag procedure.id.to_s+'/update' do%>
                        <%= hidden_field :procedure, :state, value:'2'%>
                        <select class="form-control" style='width:40%;' name="procedure[user_id]">
                            <% @users.each do |user|%>
                                <option value=<%=user.id%>> <%=user.person.first_name+' '+user.person.last_name+' '+user.current_procedures_assigned%> </option>
                            <%end%>
                        </select>
                        <%= submit_tag :Asignar ,:class=>'btn btn-primary'%>
                    <%end%>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<%end%>

app/views/procedures/begin.html.erb
<h1>Iniciar Trámite</h1>
<br/>
<% if not @projects.any? or not @procedure_types.any? %>
    <div class="row center actions">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <% if not @projects.any? %>
              <% if not @procedure_types.any? %>
                <p>En este momento no hay proyectos ni tipos de tramites disponibles para iniciar un tramite</p>
              <%else%>
                <p>En este momento no hay proyectos disponibles para iniciar un tramite</p>
              <%end%>
          <%else%>
              <p>En este momento no hay tipos de tramites disponibles para iniciar un tramite</p>
          <%end%>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-md-offset-4">
      <%= link_to 'Registrar proyecto', new_project_path ,class: 'btn btn-primary'%>
    </div>  
<%else%>
    <%= form_tag '/procedures/new', method: 'post' do %>
        <div class="col-lg-6"><br>
          <div class="panel panel-info">
            <div class="panel-heading">Elija el proyecto</div>
            <ul class="list-group">
              <%@projects.each do |project| %>
                  <div class="radio">
                    <li class="list-group-item">
                      <label>
                        <%= radio_button_tag 'project_id' ,project.id, true%>
                        <%= project.company.name%> >> <%=project.name%>
                      </label>
                    </li>
                  </div><!-- /input-group -->
              <%end%>
            </ul>
          </div>
          <br/>
        </div>
        <div class="col-lg-5"><br/>
          <h4>Tipo de tramite</h4>
          <%= select_tag :procedure_type_id, options_from_collection_for_select(@procedure_types , 'id', 'name'), class:'form-control'%>
          <br/>
          <center><%= submit_tag :Iniciar, :class=>'btn btn-default'%></center>
        </div>
    <% end %>
<%end%>

app/views/procedures/index.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<div class="row">
  <div class="col-md-7">
    <h1>Buscar Tramite </h1>
    <br>
  </div>
  <div class="col-md-5">
    <%= render :partial => 'procedures/search' %>
    <div class="form-inline">
      <br>
      <%= form_tag( procedures_path , :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Nombre de proyecto", :class=>'form-control' %>
          <%= submit_tag "Buscar" ,:class=>'btn btn-default'%>
      <% end %>
    </div>
  </div>
</div>
<h1>Lista de Tramites</h1>
<br>

<%if @procedures.empty? %>
    <div class="row center actions">
      <div class="panel panel-danger">
        <div class="panel-heading">
          En este momento no hay tramites disponibles para mostrar.
        </div>
      </div>
    </div>
<% else %>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Proyecto</th>
          <th>Estado</th>
          <th>RL</th>
          <th>Revisor</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody class="cream-pixels">
        <% @procedures.each do |procedure| %>
          <tr>
            <td><%= procedure.project.name %></td>
            <td><%if procedure.state == 1 %>
                  <h4><span class="label label-info">Inicial</span></h4>
              <%elsif procedure.state == 2 %>
                  <h4><span class="label label-warning">En revision</span></h4>
              <%elsif procedure.state == 3 %>
                  <h4><span class="label label-primary">Revisado</span></h4>
              <%elsif procedure.state == 4 %>
                  <h4><span class="label label-success">Aceptado</span></h4>
              <%else%>
                  <h4><span class="label label-danger">Rechazado</span></h4>
              <%end%>
            </td>
            <td><%= procedure.legal_agent.person.first_name %> <%= procedure.legal_agent.person.last_name %></td>
            <td>
                <%if procedure.user %>
                  <%= procedure.user.person.first_name %> <%= procedure.user.person.last_name %>
                <%else%>
                  Ningun revisor asignado
              <%end%>
            </td>
            <td><%= link_to 'Ver', procedure , class:'btn btn-default'%></td>
            <%if current_user.role==1 or current_user.role==4 %>
                <td><%= link_to 'Eliminar', procedure, method: :delete, data: { confirm: 'Confirmacion?'}, class:'btn btn-danger'  %></td>
            <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>

<br>

<%end%>

app/views/procedures/new.html.erb
<h1>Recepción de documentos</h1>

<%= render 'form' %>

<!--%= link_to 'Back', procedures_path, :class=>'btn btn-default' %>-->

app/views/procedures/show.html.erb
<%= render :partial => 'static_pages/notice_panel' %>

<h1>Ver Tramite</h1>
<br/>
<div class="row">
  <div class="col-md-6">
    <%= link_to 'Volver', procedures_path , class:'btn btn-default'%>
  </div>
  <div class="col-md-6">
    <%if current_user.role ==4 or current_user.role == 1#JEFE(4) #ADMIN(1) %>
        <%if @procedure.state==1 %>
            <%= link_to 'Asignar revisor', '/procedures/assign' , class:'btn btn-warning'%>
        <%end%>
        <%if @procedure.state==3 #Initial, revision and revised %>
            <%= form_tag '/procedures/'+@procedure.id.to_s+'/finish' do%>
                <%= submit_tag 'Finalizar Tramite' ,:class=>'btn btn-warning'%>
                <br/><br>
                <%= label_tag 'Aceptado' %>
                <%= radio_button_tag :finished, :yes , true%>
                <%= label_tag 'Rechazado' %>
                <%= radio_button_tag :finished, :no %>
            <%end%>
        <%end%>
    <%end%>

    <%if current_user.role == 5 or current_user.role == 1 #REVISOR(5) o Admin(1)%>
        <%if @procedure.state==2 && @procedure.can_be_sent_to_chief? %>
            <%= form_tag '/procedures/'+@procedure.id.to_s+'/send' do%>
                <%= submit_tag 'Enviar tramite a Jefe' ,:class=>'btn btn-warning'%>
            <%end%>
        <%end%>
    <%end%>
  </div>
</div>

<br/>
<div class="jumbotron">
    <center><h3><strong>Tipo de Trámite</strong> <%= @procedure.procedure_type.name%></h3></center>
    <center><h3><strong>Proyecto</strong> <%=@procedure.project.name%></h3></center>
    <center><h4><strong>Compañia</strong> <%=@procedure.project.company.name%></h4></center>
    <center>
      <%if @procedure.state == 1 %>
          <h4><span class="label label-info">Inicial</span></h4>
      <%elsif @procedure.state == 2 %>
          <h4><span class="label label-warning">En revision</span></h4>
      <%elsif @procedure.state == 3 %>
          <h4><span class="label label-primary">Revisado</span></h4>
      <%elsif @procedure.state == 4 %>
          <h4><span class="label label-success">Aceptado</span></h4>
      <%else%>
          <h4><span class="label label-danger">Rechazado</span></h4>
      <%end%>
    </center>
  <br/>
  <table class="table">
    <tr>
      <td><strong>Representante Legal</strong></td>
      <td><%= @procedure.legal_agent.person.first_name %>&nbsp; <%= @procedure.legal_agent.person.last_name %>     </td>
      <td><strong>Revisor</strong></td>
      <td>
        <%if @procedure.user %>
            <%= @procedure.user.person.first_name %>
            <%= @procedure.user.person.last_name %>
        <%else%>
            Ningun revisor fue asignado a este tramite todavia
        <%end%>
      </td>
    </tr>
    <tr>
      <td><strong>Fecha de inicio</strong></td>
      <td><%= @procedure.start_date.strftime('%d/%m/%Y') %></td>
      <td><strong>Fecha de conclusion</strong></td>
      <td>
        <%if @procedure.end_date %>
            <%= @procedure.end_date.strftime('%d/%m/%Y') %>
        <%else%>
            Este tramite todavia no ha acabado
        <%end%>
      </td>
    </tr>
  </table>
  <br/>
  <hr/>
  <div class="text-center">
      <h3>Documentos Recibidos</h3>
  </div>
  <br/>
  <table class="table">
    <tr>
        <th>Documento</th>
        <th>Referencia</th>
    </tr>
    <% @procedure.received_documents.each do |received_document| %>
        <tr>
          <td><i class="fa fa-file-text"></i> &nbsp; <%= received_document.document.typename%></td>
          <td><%= received_document.reference %></td>
        </tr>
    <% end%>
  </table>
  <br/>
    <%if @procedure.state>1 %>
      <hr/>
      <div class="text-center"><h3>Revisión</h3></div>
        <div class="row">
          <div class="col-lg-8">
                <h3>Listas de verificaciones</h3>
                <%if @procedure.state==2 and ((current_user.role==5 and current_user==@procedure.user) or current_user.role==1)#Revisor View%>
                    <h5>Todas las listas deben ser llenadas</h5>
                    <table class="table">
                         <% @procedure.received_documents.each do |received_document| %>
                            <tr>
                              <td rowspan=<%=received_document.verified_lists.count%>>
                                <%= received_document.document.typename %>
                              </td>
                                <% received_document.verified_lists.each do |verified_list| %>
                                    <% if verified_list!=received_document.verified_lists.first then %>
                                        <tr>
                                      <%end%>
                                      <div class="form-inline">
                                        <td>
                                              <%= verified_list.verification_list.name %>
                                        </td>
                                        <td>
                                          <% if verified_list.verified %>
                                              <%= link_to :Editar, edit_verified_list_path(verified_list) ,class:'btn btn-primary'%>
                                          <%else%>
                                              <%= link_to :Revisar, edit_verified_list_path(verified_list) ,class:'btn btn-info'%>
                                          <%end%>
                                        </td>
                                      </div>
                                <%end%>
                        <%end%>
                    </table>
                <%end%>

                <%if @procedure.state>=3 #has already a revisor assigned %>
                <table class="table">
                  <% @procedure.received_documents.each do |received_document| %>
                      <tr>
                        <td rowspan=<%=received_document.verified_lists.count%>>
                          <%= received_document.document.typename %>
                        </td>
                        <% received_document.verified_lists.each do |verified_list| %>
                            <% if verified_list!=received_document.verified_lists.first then %>
                              <tr>
                          <%end%>
                            <td><%= verified_list.verification_list.name %></td>
                            <td><%= link_to :Ver, verified_list,class:'btn btn-default' %> </td>
                          </tr>
                      <%end%>

                  <%end%>
                </table>
                <%end%>
          </div>

          <div class="col-lg-4">
            <h3>Informe</h3>
                <% if @procedure.state == 2%>
                    <% if (current_user.role == 5 and current_user==@procedure.user) or current_user.role==1 %>
                        <% if @procedure.report %>
                            <h4>Edite el informe <%= link_to 'aqui', edit_report_path(@procedure.report) %></h4>
                        <%else%>
                            <%= link_to 'Registrar Informe', '/reports/new/'+@procedure.id.to_s , class:'btn btn-info'%>
                        <%end%>
                    <%end%>
                <%else%>
                    <h4>Vea el informe <%= link_to 'aqui', @procedure.report %></h4>
                <% end %>
          </div>
        </div>
    <% end %>

</div>

<br/><br/>